### ISSUE TITLE
Help with the stolen funds

### ISSUE THREAD

**Issue by KingZee** [1400BitcoinStolen/1400BitcoinStolen#3]
You should probably get notified with this issue I hope, I have an idea to help. I'd rather keep public details minimal for obvious reasons, shoot me an e-mail very soon (visible from my github profile). I'll try to do my best.

**Comment by KingZee** [comment]
@1400BitcoinStolen

**Comment by KingZee** [comment]
@1400BitcoinStolen

**Comment by 1400BitcoinStolen** [comment]
hi, what do you have in mind. Are you another scammer?

**Comment by KingZee** [comment]
Hi! I really just want to help. Send me an e-mail, I'll tell you everything in detail in private, you're free to believe me or not then.

**Comment by 1400BitcoinStolen** [comment]
I am not prepared to share my email at this point in fear of downloading malware. Thanks anyway.

**Comment by KingZee** [comment]
I just realized you get the full comment text in e-mail, so I'll make this comment and delete it in a few minutes : 

I made a new e-mail : forhundredbits@gmail.com, pass : 1400bits.

It has nothing for now, you can login and change the password if you like. I'll email you on it in a bit.

**Comment by 1400BitcoinStolen** [comment]
I captured the email however I am still nervous.

**Comment by 1400BitcoinStolen** [comment]
I may still be subject to downloading malware

**Comment by KingZee** [comment]
I will not send you any links. I understand your panic, but for now simply login on gmail, i'll send you the full text of what I plan to do, and you can decide for yourself.

**Comment by 1400BitcoinStolen** [comment]
I welcome your plan to be written here.

**Comment by 1400BitcoinStolen** [comment]
If not thanks for your time

**Comment by KingZee** [comment]
If you like. for your sake I hope the thief is not reading this. I plan to help you contact every possible way to exchange the coins into money / different coins, and catch your funds if they reach any centralized wallet. Saying this in public though completely alarms the thief, but you asked for it.

Your funds are currently spread out on 5 addresses here : 

bc1qyzxepepphr4f53577v8mrn5quyk0jjvjxh34mx
bc1qt4w97nlatj40ya8fkkxeng235earyr0lh0j079
bc1qs54aqpcx3729cty3tuad4kzsru65l62mdja7hs
bc1qf8a68mrn93qv7s8r5lgusyqf5cpdka2yuf0crp
bc1q5fvlcfg33ae6wvuf7dz8fpnj9w7qfplekedqf0

**Comment by KingZee** [comment]
The thing is that this requires diligent work in trying to close off every possible exit the coins can go through. and in being constantly on alert to monitor when the funds move.

**Comment by 1400BitcoinStolen** [comment]
yes I have tracked those addresses myself

**Comment by 1400BitcoinStolen** [comment]
If they put them through a mixer it is all over

**Comment by 1400BitcoinStolen** [comment]
Provided it is an effective mixer

**Comment by KingZee** [comment]
It's not :) Mixers are controlled by people.

**Comment by KingZee** [comment]
I'm really trying to help you here, I know it hurts, but if you're coming into this with a defeated attitude...

**Comment by 1400BitcoinStolen** [comment]
How much are you seeking for your services?

**Comment by KingZee** [comment]
LOL I'm not asking for pay

**Comment by KingZee** [comment]
a tip when/if you get them back would be welcome, but it's your money really

**Comment by 1400BitcoinStolen** [comment]
ofcourse I would pay a percentage

**Comment by 1400BitcoinStolen** [comment]
upon success

**Comment by 1400BitcoinStolen** [comment]
But this is going to a long road. Engaging law enforcement, lawyers later for a civil suit providing the criminals are identified and charged.

**Comment by KingZee** [comment]
That part is unfortunately on you, you need to file a police report within your local country first. No one can do much on your behalf legally unless you have a case yourself

**Comment by 1400BitcoinStolen** [comment]
true

**Comment by KingZee** [comment]
I have to go offline, you have the e-mail, you're free to contact me through it in the future, it might be a nice idea to delete comments here. For now opening a police report is the first thing you should do, as you will be asked for it by exchanges, after that it's just time and effort and hope

**Comment by 1400BitcoinStolen** [comment]
please delete all comms, I have recorded this chat

**Comment by KingZee** [comment]
I think you should have a button to delete the entire issue on the rightside of the conversation.
