### ISSUE TITLE
i know him!

### ISSUE THREAD

**Issue by ikw30** [1400BitcoinStolen/1400BitcoinStolen#6]
Hi, after i read the article about the stolen btc, i realised who was behind of this operation. I was a part of the team that made the virus that infected you. After some discussion with the team members we split up, but my work remained on their behalf.
So, today i tried to get ahold of them but they didn't wanted to respond to my messages.I decided to help you with some essential informations about the members. When i worked with them we used sometimes remote access , that's how i found out the real name of one of them.(His personal facebook page was open when i logged in his computer). The second member has made me transfer on my Revolut account.( i don't know if he used his revolut or someone else's account - but it can help you).

So, if you want these informations, you need to pay 100 BTC, 75 btc first , and 25 after i give you the details. 

My BTC address : 363BHv6XzdUBFXm16D5oW9kgUvYqssG2wb

You decide if you want to reach them, i just want my work paid. I know that this message can seem a scam, but you lost 1400 BTC, think about this.

After you paid the first 75 btc, i write here all the informations.

I hope you will make the right decision.

**Comment by nodesocket** [comment]
Leave this poor guy alone troll.

**Comment by explorer-cash** [comment]
Lol, he is a liar. He posted the same message in 2019 : 

https://bitcointalk.org/index.php?topic=5182537.msg52383421#msg52383421

A pure hoax to move people out of Electrum.
